name: CI
on:
  push:
  schedule:
    - cron: 13 01 * * *

jobs:
  docker-build-cache:
    name: docker build cache
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: fluree/db
          load: true
      - name: Run tests
        run: script/run-in-docker.sh ls

  # test-nodejs:
  #   name: test flureenjs.js
  #   needs: docker-build-cache
  #   runs-on: [linux, large, docker]
  #   steps:
  #     - uses: actions/checkout@v3.1.0
  #     - uses: docker/setup-buildx-action@v2.2.1
  #       with:
  #         install: true
  #     - uses: docker/build-push-action@v3
  #       with:
  #         context: .
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max
  #         tags: fluree/db
  #         load: true
  #     - name: Run tests
  #       run: script/run-in-docker.sh make nodejs-test

  test-browser:
    name: test flureedb.js
    needs: docker-build-cache
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: fluree/db
          load: true
      - name: Run tests
        run: script/run-in-docker.sh make browser-test

  test-clj:
    name: run clj tests
    needs: docker-build-cache
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: fluree/db
          load: true
      - name: Run tests
        run: script/run-in-docker.sh make cljtest eastwood nodejs-test

  test-cljs:
    name: run cljs tests
    needs: docker-build-cache
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: fluree/db
          load: true
      - name: Run tests
        run: script/run-in-docker.sh make cljstest
