name: CI
on:
  push:
  schedule:
    - cron: 13 01 * * *

jobs:
  docker-layer-cache:
    name: Build with Docker
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2.2.1
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: fluree/db
          outputs: type=docker,dest=/tmp/myiamge.tar

  test-clj:
    name: run clj & cljs tests
    needs: docker-layer-cache
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
      - name: Run tests
        run: script/run-in-docker.sh make cljtest
  test-nodejs:
    name: run nodejs tests
    needs: docker-layer-cache
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
       - name: Run tests
        run: script/run-in-docker.sh make nodejs-test
  test-browser:
    name: run browser tests
    needs: docker-layer-cache
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
       - name: Run tests
        run: script/run-in-docker.sh make browser-test
  test-eastwood:
    name: run eastwood
    needs: docker-layer-cache
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
       - name: Run tests
        run: script/run-in-docker.sh make eastwood
  build-docker:
    name: build Docker image
    needs: [test-clj, test-nodejs, test-browser, test-eastwood]
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Build Docker image
        run: docker build -t fluree/db .
      - name: Notify Slack fail
        if: github.ref == 'refs/heads/main' && failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v2
        with:
          channel_id: CNCH08G14 # development channel
          status: FAILED
          color: danger
