name: CI
on:
  push:
  schedule:
    - cron: 13 01 * * *

jobs:
  docker-layer-cache:
    name: Build with Docker
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2.2.1
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: fluree/db
          load: true
      - run: script/run-in-docker.sh ls

  docker-layer-cache-2:
    name: Build with Docker
    needs: docker-layer-cache
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2.2.1
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: fluree/db
          load: true
      - run: script/run-in-docker.sh ls
