name: CI
on:
  push:
  schedule:
    - cron: 13 01 * * *

# Docker image artifact uploading & downloading approach is the one suggested
# here for sharing Docker images between jobs:
# https://docs.docker.com/build/ci/github-actions/examples/#share-built-image-between-jobs

jobs:
  docker-build-cache:
    name: docker build cache
    runs-on: [linux, large, docker]
    outputs:
      docker-image: ${{ steps.build.outputs.imageid }}
    steps:
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - uses: docker/build-push-action@v3
        id: build
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: fluree/db
          outputs: type=docker,dest=/tmp/docker-image.tar
      - uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/docker-image.tar

  test-nodejs:
    name: test flureenjs.js
    needs: docker-build-cache
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/docker-image.tar
          docker image ls -a
      - name: Run tests
        run: docker run ${{ needs.docker-build-cache.outputs.docker-image }} make nodejs-test

#  test-browser:
#    name: test flureedb.js
#    needs: docker-build-cache
#    runs-on: [linux, large, docker]
#    steps:
#      - uses: docker/setup-buildx-action@v2.2.1
#        with:
#          install: true
#      - uses: docker/build-push-action@v3
#        with:
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#          tags: fluree/db
#          load: true
#      - name: Run tests
#        run: script/run-in-docker.sh make browser-test
#
#  test-clj:
#    name: run clj tests
#    needs: docker-build-cache
#    runs-on: [linux, large, docker]
#    steps:
#      - uses: docker/setup-buildx-action@v2.2.1
#        with:
#          install: true
#      - uses: docker/build-push-action@v3
#        with:
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#          tags: fluree/db
#          load: true
#      - name: Run tests
#        run: script/run-in-docker.sh make cljtest eastwood nodejs-test
#
#  test-cljs:
#    name: run cljs tests
#    needs: docker-build-cache
#    runs-on: [linux, large, docker]
#    steps:
#      - uses: docker/setup-buildx-action@v2.2.1
#        with:
#          install: true
#      - uses: docker/build-push-action@v3
#        with:
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#          tags: fluree/db
#          load: true
#      - name: Run tests
#        run: script/run-in-docker.sh make cljstest
