name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: 13 01 * * *

jobs:
  test-clj:
    name: run clj tests
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Run tests
        run: script/run-in-docker.sh make cljtest
  test-cljs:
    name: run cljs tests
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Run tests
        run: script/run-in-docker.sh make cljstest
  test-nodejs:
    name: run nodejs tests
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Run tests
        run: script/run-in-docker.sh make nodejs-test
  test-browser:
    name: run browser tests
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Run tests
        run: script/run-in-docker.sh make browser-test
  test-eastwood:
    name: run eastwood
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Run tests
        run: script/run-in-docker.sh make eastwood
  build-docker:
    name: build Docker image
    needs: [test-clj, test-cljs, test-nodejs, test-browser, test-eastwood]
    runs-on: [linux, large, docker]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Run tests
        run: script/run-in-docker.sh make ci
      - name: Build Docker image
        run: docker build -t fluree/db .
      - name: Notify Slack fail
        if: github.ref == 'refs/heads/main' && failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v2
        with:
          channel_id: CNCH08G14 # development channel
          status: FAILED
          color: danger
